//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMX360.DAL.Seguridad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CMX360SeguridadEntities : DbContext
    {
        public CMX360SeguridadEntities()
            : base("name=CMX360SeguridadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<spCategoriaImagenCn_Result> spCategoriaImagenCn()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCategoriaImagenCn_Result>("spCategoriaImagenCn");
        }
    
        public virtual ObjectResult<spFPSAplicacionCn_Result> spFPSAplicacionCn()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFPSAplicacionCn_Result>("spFPSAplicacionCn");
        }
    
        public virtual int spFPSaUsuarioAlmacenDel(string usrAPP, Nullable<int> idAlmacen)
        {
            var usrAPPParameter = usrAPP != null ?
                new ObjectParameter("usrAPP", usrAPP) :
                new ObjectParameter("usrAPP", typeof(string));
    
            var idAlmacenParameter = idAlmacen.HasValue ?
                new ObjectParameter("IdAlmacen", idAlmacen) :
                new ObjectParameter("IdAlmacen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spFPSaUsuarioAlmacenDel", usrAPPParameter, idAlmacenParameter);
        }
    
        public virtual int spFPSaUsuarioAlmacenIn(string usrAPP, Nullable<int> idAlmacen, Nullable<bool> banActivo, string usrAlta)
        {
            var usrAPPParameter = usrAPP != null ?
                new ObjectParameter("usrAPP", usrAPP) :
                new ObjectParameter("usrAPP", typeof(string));
    
            var idAlmacenParameter = idAlmacen.HasValue ?
                new ObjectParameter("IdAlmacen", idAlmacen) :
                new ObjectParameter("IdAlmacen", typeof(int));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("BanActivo", banActivo) :
                new ObjectParameter("BanActivo", typeof(bool));
    
            var usrAltaParameter = usrAlta != null ?
                new ObjectParameter("UsrAlta", usrAlta) :
                new ObjectParameter("UsrAlta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spFPSaUsuarioAlmacenIn", usrAPPParameter, idAlmacenParameter, banActivoParameter, usrAltaParameter);
        }
    
        public virtual ObjectResult<spImagenMenuCn_Result> spImagenMenuCn(Nullable<int> idCategoria)
        {
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("idCategoria", idCategoria) :
                new ObjectParameter("idCategoria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spImagenMenuCn_Result>("spImagenMenuCn", idCategoriaParameter);
        }
    
        public virtual int spIVSUsuariosIn(string usrAPP, string nomNombre, string nomAPaterno, string nomAMaterno, string correo, string providerKey, string provider, string usrAlta, string id, string contraseña, string llaveActicacion, Nullable<System.DateTime> fechaCadudaLlave, Nullable<System.DateTime> fechaCorreoValidado, Nullable<bool> correoValidado)
        {
            var usrAPPParameter = usrAPP != null ?
                new ObjectParameter("usrAPP", usrAPP) :
                new ObjectParameter("usrAPP", typeof(string));
    
            var nomNombreParameter = nomNombre != null ?
                new ObjectParameter("nomNombre", nomNombre) :
                new ObjectParameter("nomNombre", typeof(string));
    
            var nomAPaternoParameter = nomAPaterno != null ?
                new ObjectParameter("nomAPaterno", nomAPaterno) :
                new ObjectParameter("nomAPaterno", typeof(string));
    
            var nomAMaternoParameter = nomAMaterno != null ?
                new ObjectParameter("nomAMaterno", nomAMaterno) :
                new ObjectParameter("nomAMaterno", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var providerKeyParameter = providerKey != null ?
                new ObjectParameter("ProviderKey", providerKey) :
                new ObjectParameter("ProviderKey", typeof(string));
    
            var providerParameter = provider != null ?
                new ObjectParameter("Provider", provider) :
                new ObjectParameter("Provider", typeof(string));
    
            var usrAltaParameter = usrAlta != null ?
                new ObjectParameter("usrAlta", usrAlta) :
                new ObjectParameter("usrAlta", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("contraseña", contraseña) :
                new ObjectParameter("contraseña", typeof(string));
    
            var llaveActicacionParameter = llaveActicacion != null ?
                new ObjectParameter("LlaveActicacion", llaveActicacion) :
                new ObjectParameter("LlaveActicacion", typeof(string));
    
            var fechaCadudaLlaveParameter = fechaCadudaLlave.HasValue ?
                new ObjectParameter("FechaCadudaLlave", fechaCadudaLlave) :
                new ObjectParameter("FechaCadudaLlave", typeof(System.DateTime));
    
            var fechaCorreoValidadoParameter = fechaCorreoValidado.HasValue ?
                new ObjectParameter("FechaCorreoValidado", fechaCorreoValidado) :
                new ObjectParameter("FechaCorreoValidado", typeof(System.DateTime));
    
            var correoValidadoParameter = correoValidado.HasValue ?
                new ObjectParameter("CorreoValidado", correoValidado) :
                new ObjectParameter("CorreoValidado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spIVSUsuariosIn", usrAPPParameter, nomNombreParameter, nomAPaternoParameter, nomAMaternoParameter, correoParameter, providerKeyParameter, providerParameter, usrAltaParameter, idParameter, contraseñaParameter, llaveActicacionParameter, fechaCadudaLlaveParameter, fechaCorreoValidadoParameter, correoValidadoParameter);
        }
    
        public virtual ObjectResult<spIVXLoginLocal_Result> spIVXLoginLocal(string usuario, string pASSWORD)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spIVXLoginLocal_Result>("spIVXLoginLocal", usuarioParameter, pASSWORDParameter);
        }
    
        public virtual ObjectResult<spIVXUsuariosCn_Result> spIVXUsuariosCn(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spIVXUsuariosCn_Result>("spIVXUsuariosCn", usuarioParameter);
        }
    
        public virtual ObjectResult<spPaginaPermisoRolCn_Result> spPaginaPermisoRolCn(Nullable<long> idPagina)
        {
            var idPaginaParameter = idPagina.HasValue ?
                new ObjectParameter("idPagina", idPagina) :
                new ObjectParameter("idPagina", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spPaginaPermisoRolCn_Result>("spPaginaPermisoRolCn", idPaginaParameter);
        }
    
        public virtual int spPaginaPermisoRolEl(Nullable<long> idRol, Nullable<long> idPagina, Nullable<long> idPermiso)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(long));
    
            var idPaginaParameter = idPagina.HasValue ?
                new ObjectParameter("idPagina", idPagina) :
                new ObjectParameter("idPagina", typeof(long));
    
            var idPermisoParameter = idPermiso.HasValue ?
                new ObjectParameter("idPermiso", idPermiso) :
                new ObjectParameter("idPermiso", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spPaginaPermisoRolEl", idRolParameter, idPaginaParameter, idPermisoParameter);
        }
    
        public virtual ObjectResult<spPaginasRolCn_Result> spPaginasRolCn(Nullable<int> idRol)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spPaginasRolCn_Result>("spPaginasRolCn", idRolParameter);
        }
    
        public virtual int spRESCambioContrasenia(string correo, string usrAPP)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var usrAPPParameter = usrAPP != null ?
                new ObjectParameter("usrAPP", usrAPP) :
                new ObjectParameter("usrAPP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESCambioContrasenia", correoParameter, usrAPPParameter);
        }
    
        public virtual ObjectResult<spRESCnaPermisoEspecial_Result> spRESCnaPermisoEspecial(string usrAPP)
        {
            var usrAPPParameter = usrAPP != null ?
                new ObjectParameter("usrAPP", usrAPP) :
                new ObjectParameter("usrAPP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRESCnaPermisoEspecial_Result>("spRESCnaPermisoEspecial", usrAPPParameter);
        }
    
        public virtual ObjectResult<spRESCnaRolPaginaPermiso_Result> spRESCnaRolPaginaPermiso(Nullable<long> idRol, Nullable<long> idPagina)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(long));
    
            var idPaginaParameter = idPagina.HasValue ?
                new ObjectParameter("idPagina", idPagina) :
                new ObjectParameter("idPagina", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRESCnaRolPaginaPermiso_Result>("spRESCnaRolPaginaPermiso", idRolParameter, idPaginaParameter);
        }
    
        public virtual ObjectResult<spRESCnaRolUsuario_Result> spRESCnaRolUsuario(string usrAPP, Nullable<int> idAplicacion)
        {
            var usrAPPParameter = usrAPP != null ?
                new ObjectParameter("usrAPP", usrAPP) :
                new ObjectParameter("usrAPP", typeof(string));
    
            var idAplicacionParameter = idAplicacion.HasValue ?
                new ObjectParameter("idAplicacion", idAplicacion) :
                new ObjectParameter("idAplicacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRESCnaRolUsuario_Result>("spRESCnaRolUsuario", usrAPPParameter, idAplicacionParameter);
        }
    
        public virtual ObjectResult<spRESCncAplicacion_Result> spRESCncAplicacion(Nullable<long> idAplicacion)
        {
            var idAplicacionParameter = idAplicacion.HasValue ?
                new ObjectParameter("idAplicacion", idAplicacion) :
                new ObjectParameter("idAplicacion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRESCncAplicacion_Result>("spRESCncAplicacion", idAplicacionParameter);
        }
    
        public virtual ObjectResult<spRESCncPagina_Result> spRESCncPagina(Nullable<long> idPagina, string nomPagina, Nullable<long> idAplicacion)
        {
            var idPaginaParameter = idPagina.HasValue ?
                new ObjectParameter("idPagina", idPagina) :
                new ObjectParameter("idPagina", typeof(long));
    
            var nomPaginaParameter = nomPagina != null ?
                new ObjectParameter("nomPagina", nomPagina) :
                new ObjectParameter("nomPagina", typeof(string));
    
            var idAplicacionParameter = idAplicacion.HasValue ?
                new ObjectParameter("idAplicacion", idAplicacion) :
                new ObjectParameter("idAplicacion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRESCncPagina_Result>("spRESCncPagina", idPaginaParameter, nomPaginaParameter, idAplicacionParameter);
        }
    
        public virtual ObjectResult<spRESCncPaginaPermiso_Result> spRESCncPaginaPermiso(Nullable<long> idPagina)
        {
            var idPaginaParameter = idPagina.HasValue ?
                new ObjectParameter("idPagina", idPagina) :
                new ObjectParameter("idPagina", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRESCncPaginaPermiso_Result>("spRESCncPaginaPermiso", idPaginaParameter);
        }
    
        public virtual ObjectResult<spRESCncPermiso_Result> spRESCncPermiso(Nullable<long> idPermiso)
        {
            var idPermisoParameter = idPermiso.HasValue ?
                new ObjectParameter("idPermiso", idPermiso) :
                new ObjectParameter("idPermiso", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRESCncPermiso_Result>("spRESCncPermiso", idPermisoParameter);
        }
    
        public virtual ObjectResult<spRESCncRol_Result> spRESCncRol(Nullable<long> idRol)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRESCncRol_Result>("spRESCncRol", idRolParameter);
        }
    
        public virtual ObjectResult<spRESCtaAplicacionRol_Result> spRESCtaAplicacionRol(Nullable<long> idAplicacion)
        {
            var idAplicacionParameter = idAplicacion.HasValue ?
                new ObjectParameter("idAplicacion", idAplicacion) :
                new ObjectParameter("idAplicacion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRESCtaAplicacionRol_Result>("spRESCtaAplicacionRol", idAplicacionParameter);
        }
    
        public virtual int spRESCtaBackProcess(Nullable<int> idAplicacion, Nullable<bool> banActivo)
        {
            var idAplicacionParameter = idAplicacion.HasValue ?
                new ObjectParameter("idAplicacion", idAplicacion) :
                new ObjectParameter("idAplicacion", typeof(int));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESCtaBackProcess", idAplicacionParameter, banActivoParameter);
        }
    
        public virtual int spRESCtaBackProcessLog(Nullable<int> idBackProcess)
        {
            var idBackProcessParameter = idBackProcess.HasValue ?
                new ObjectParameter("idBackProcess", idBackProcess) :
                new ObjectParameter("idBackProcess", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESCtaBackProcessLog", idBackProcessParameter);
        }
    
        public virtual int spRESCtaBackProcessLogUltimaEjecucion(Nullable<int> idBackProcess)
        {
            var idBackProcessParameter = idBackProcess.HasValue ?
                new ObjectParameter("idBackProcess", idBackProcess) :
                new ObjectParameter("idBackProcess", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESCtaBackProcessLogUltimaEjecucion", idBackProcessParameter);
        }
    
        public virtual ObjectResult<spRESCtaLogError_Result> spRESCtaLogError(Nullable<bool> idAplicacion)
        {
            var idAplicacionParameter = idAplicacion.HasValue ?
                new ObjectParameter("idAplicacion", idAplicacion) :
                new ObjectParameter("idAplicacion", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRESCtaLogError_Result>("spRESCtaLogError", idAplicacionParameter);
        }
    
        public virtual ObjectResult<spRESCtaPermisoEspecial_Result> spRESCtaPermisoEspecial(Nullable<bool> banActivo)
        {
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRESCtaPermisoEspecial_Result>("spRESCtaPermisoEspecial", banActivoParameter);
        }
    
        public virtual ObjectResult<spRESCtcAplicacion_Result> spRESCtcAplicacion(Nullable<bool> banActivo)
        {
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRESCtcAplicacion_Result>("spRESCtcAplicacion", banActivoParameter);
        }
    
        public virtual ObjectResult<spRESCtcPagina_Result> spRESCtcPagina(Nullable<long> idAplicacion, Nullable<bool> banActivo)
        {
            var idAplicacionParameter = idAplicacion.HasValue ?
                new ObjectParameter("idAplicacion", idAplicacion) :
                new ObjectParameter("idAplicacion", typeof(long));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRESCtcPagina_Result>("spRESCtcPagina", idAplicacionParameter, banActivoParameter);
        }
    
        public virtual ObjectResult<spRESCtcPaginaPermiso_Result> spRESCtcPaginaPermiso(Nullable<bool> banActivo)
        {
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRESCtcPaginaPermiso_Result>("spRESCtcPaginaPermiso", banActivoParameter);
        }
    
        public virtual ObjectResult<spRESCtcPermiso_Result> spRESCtcPermiso(Nullable<bool> banActivo)
        {
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRESCtcPermiso_Result>("spRESCtcPermiso", banActivoParameter);
        }
    
        public virtual ObjectResult<spRESCtcRol_Result> spRESCtcRol(Nullable<bool> banActivo)
        {
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRESCtcRol_Result>("spRESCtcRol", banActivoParameter);
        }
    
        public virtual ObjectResult<spRESCtUsuarios_Result> spRESCtUsuarios(Nullable<long> idAplicacion, Nullable<bool> banActivo)
        {
            var idAplicacionParameter = idAplicacion.HasValue ?
                new ObjectParameter("idAplicacion", idAplicacion) :
                new ObjectParameter("idAplicacion", typeof(long));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRESCtUsuarios_Result>("spRESCtUsuarios", idAplicacionParameter, banActivoParameter);
        }
    
        public virtual int spRESDeaEstautsBackProcess(Nullable<int> idBackProcess)
        {
            var idBackProcessParameter = idBackProcess.HasValue ?
                new ObjectParameter("idBackProcess", idBackProcess) :
                new ObjectParameter("idBackProcess", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESDeaEstautsBackProcess", idBackProcessParameter);
        }
    
        public virtual int spRESDelaRolUsuario(Nullable<long> idRol, string usrAPP)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(long));
    
            var usrAPPParameter = usrAPP != null ?
                new ObjectParameter("usrAPP", usrAPP) :
                new ObjectParameter("usrAPP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESDelaRolUsuario", idRolParameter, usrAPPParameter);
        }
    
        public virtual int spRESEdaBackProcess(Nullable<int> idBackProcess, Nullable<long> idAplicacion, string nomProceso, string xmlParamteros, string nomLibreria, Nullable<bool> banActivo)
        {
            var idBackProcessParameter = idBackProcess.HasValue ?
                new ObjectParameter("idBackProcess", idBackProcess) :
                new ObjectParameter("idBackProcess", typeof(int));
    
            var idAplicacionParameter = idAplicacion.HasValue ?
                new ObjectParameter("idAplicacion", idAplicacion) :
                new ObjectParameter("idAplicacion", typeof(long));
    
            var nomProcesoParameter = nomProceso != null ?
                new ObjectParameter("nomProceso", nomProceso) :
                new ObjectParameter("nomProceso", typeof(string));
    
            var xmlParamterosParameter = xmlParamteros != null ?
                new ObjectParameter("xmlParamteros", xmlParamteros) :
                new ObjectParameter("xmlParamteros", typeof(string));
    
            var nomLibreriaParameter = nomLibreria != null ?
                new ObjectParameter("nomLibreria", nomLibreria) :
                new ObjectParameter("nomLibreria", typeof(string));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESEdaBackProcess", idBackProcessParameter, idAplicacionParameter, nomProcesoParameter, xmlParamterosParameter, nomLibreriaParameter, banActivoParameter);
        }
    
        public virtual int spRESEdaEstautsBackProcess(Nullable<int> idBackProcess, Nullable<long> banProceso)
        {
            var idBackProcessParameter = idBackProcess.HasValue ?
                new ObjectParameter("idBackProcess", idBackProcess) :
                new ObjectParameter("idBackProcess", typeof(int));
    
            var banProcesoParameter = banProceso.HasValue ?
                new ObjectParameter("banProceso", banProceso) :
                new ObjectParameter("banProceso", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESEdaEstautsBackProcess", idBackProcessParameter, banProcesoParameter);
        }
    
        public virtual int spRESEdaPermisoEspecial(string usrAPP, Nullable<long> idPagina, Nullable<long> idPermiso, Nullable<bool> banActivo, string usrMod)
        {
            var usrAPPParameter = usrAPP != null ?
                new ObjectParameter("usrAPP", usrAPP) :
                new ObjectParameter("usrAPP", typeof(string));
    
            var idPaginaParameter = idPagina.HasValue ?
                new ObjectParameter("idPagina", idPagina) :
                new ObjectParameter("idPagina", typeof(long));
    
            var idPermisoParameter = idPermiso.HasValue ?
                new ObjectParameter("idPermiso", idPermiso) :
                new ObjectParameter("idPermiso", typeof(long));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrModParameter = usrMod != null ?
                new ObjectParameter("usrMod", usrMod) :
                new ObjectParameter("usrMod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESEdaPermisoEspecial", usrAPPParameter, idPaginaParameter, idPermisoParameter, banActivoParameter, usrModParameter);
        }
    
        public virtual int spRESEdaRolPaginaPermiso(Nullable<long> idRol, Nullable<long> idPagina, Nullable<long> idPermiso, Nullable<bool> banActivo, string usrMod)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(long));
    
            var idPaginaParameter = idPagina.HasValue ?
                new ObjectParameter("idPagina", idPagina) :
                new ObjectParameter("idPagina", typeof(long));
    
            var idPermisoParameter = idPermiso.HasValue ?
                new ObjectParameter("idPermiso", idPermiso) :
                new ObjectParameter("idPermiso", typeof(long));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrModParameter = usrMod != null ?
                new ObjectParameter("usrMod", usrMod) :
                new ObjectParameter("usrMod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESEdaRolPaginaPermiso", idRolParameter, idPaginaParameter, idPermisoParameter, banActivoParameter, usrModParameter);
        }
    
        public virtual int spRESEdcAplicacion(Nullable<long> idAplicacion, string nomAplicacion, string xmlParametros, Nullable<bool> banActivo, string usrMod)
        {
            var idAplicacionParameter = idAplicacion.HasValue ?
                new ObjectParameter("idAplicacion", idAplicacion) :
                new ObjectParameter("idAplicacion", typeof(long));
    
            var nomAplicacionParameter = nomAplicacion != null ?
                new ObjectParameter("nomAplicacion", nomAplicacion) :
                new ObjectParameter("nomAplicacion", typeof(string));
    
            var xmlParametrosParameter = xmlParametros != null ?
                new ObjectParameter("xmlParametros", xmlParametros) :
                new ObjectParameter("xmlParametros", typeof(string));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrModParameter = usrMod != null ?
                new ObjectParameter("usrMod", usrMod) :
                new ObjectParameter("usrMod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESEdcAplicacion", idAplicacionParameter, nomAplicacionParameter, xmlParametrosParameter, banActivoParameter, usrModParameter);
        }
    
        public virtual int spRESEdcPagina(Nullable<long> idPagina, Nullable<long> idAplicacion, string nomPagina, Nullable<long> idPaginaPadre, string nomMenu, string url, string imgMenu, Nullable<bool> banActivo, string usrMod)
        {
            var idPaginaParameter = idPagina.HasValue ?
                new ObjectParameter("idPagina", idPagina) :
                new ObjectParameter("idPagina", typeof(long));
    
            var idAplicacionParameter = idAplicacion.HasValue ?
                new ObjectParameter("idAplicacion", idAplicacion) :
                new ObjectParameter("idAplicacion", typeof(long));
    
            var nomPaginaParameter = nomPagina != null ?
                new ObjectParameter("nomPagina", nomPagina) :
                new ObjectParameter("nomPagina", typeof(string));
    
            var idPaginaPadreParameter = idPaginaPadre.HasValue ?
                new ObjectParameter("idPaginaPadre", idPaginaPadre) :
                new ObjectParameter("idPaginaPadre", typeof(long));
    
            var nomMenuParameter = nomMenu != null ?
                new ObjectParameter("nomMenu", nomMenu) :
                new ObjectParameter("nomMenu", typeof(string));
    
            var urlParameter = url != null ?
                new ObjectParameter("url", url) :
                new ObjectParameter("url", typeof(string));
    
            var imgMenuParameter = imgMenu != null ?
                new ObjectParameter("imgMenu", imgMenu) :
                new ObjectParameter("imgMenu", typeof(string));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrModParameter = usrMod != null ?
                new ObjectParameter("usrMod", usrMod) :
                new ObjectParameter("usrMod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESEdcPagina", idPaginaParameter, idAplicacionParameter, nomPaginaParameter, idPaginaPadreParameter, nomMenuParameter, urlParameter, imgMenuParameter, banActivoParameter, usrModParameter);
        }
    
        public virtual int spRESEdcPaginaPermiso(Nullable<long> idPagina, Nullable<long> idPermiso, Nullable<bool> banActivo, string usrMod)
        {
            var idPaginaParameter = idPagina.HasValue ?
                new ObjectParameter("idPagina", idPagina) :
                new ObjectParameter("idPagina", typeof(long));
    
            var idPermisoParameter = idPermiso.HasValue ?
                new ObjectParameter("idPermiso", idPermiso) :
                new ObjectParameter("idPermiso", typeof(long));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrModParameter = usrMod != null ?
                new ObjectParameter("usrMod", usrMod) :
                new ObjectParameter("usrMod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESEdcPaginaPermiso", idPaginaParameter, idPermisoParameter, banActivoParameter, usrModParameter);
        }
    
        public virtual int spRESEdcPermiso(Nullable<long> idPermiso, string nomPermiso, Nullable<bool> banActivo, string usrMod)
        {
            var idPermisoParameter = idPermiso.HasValue ?
                new ObjectParameter("idPermiso", idPermiso) :
                new ObjectParameter("idPermiso", typeof(long));
    
            var nomPermisoParameter = nomPermiso != null ?
                new ObjectParameter("nomPermiso", nomPermiso) :
                new ObjectParameter("nomPermiso", typeof(string));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrModParameter = usrMod != null ?
                new ObjectParameter("usrMod", usrMod) :
                new ObjectParameter("usrMod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESEdcPermiso", idPermisoParameter, nomPermisoParameter, banActivoParameter, usrModParameter);
        }
    
        public virtual int spRESEdcRol(Nullable<long> idRol, string nomRol, Nullable<bool> banActivo, string usrMod)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(long));
    
            var nomRolParameter = nomRol != null ?
                new ObjectParameter("nomRol", nomRol) :
                new ObjectParameter("nomRol", typeof(string));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrModParameter = usrMod != null ?
                new ObjectParameter("usrMod", usrMod) :
                new ObjectParameter("usrMod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESEdcRol", idRolParameter, nomRolParameter, banActivoParameter, usrModParameter);
        }
    
        public virtual int spRESEdUsuarios(string usrAPP, string nomNombre, string nomAPaterno, string nomAMaterno, Nullable<bool> banActivo, string usrMod)
        {
            var usrAPPParameter = usrAPP != null ?
                new ObjectParameter("usrAPP", usrAPP) :
                new ObjectParameter("usrAPP", typeof(string));
    
            var nomNombreParameter = nomNombre != null ?
                new ObjectParameter("nomNombre", nomNombre) :
                new ObjectParameter("nomNombre", typeof(string));
    
            var nomAPaternoParameter = nomAPaterno != null ?
                new ObjectParameter("nomAPaterno", nomAPaterno) :
                new ObjectParameter("nomAPaterno", typeof(string));
    
            var nomAMaternoParameter = nomAMaterno != null ?
                new ObjectParameter("nomAMaterno", nomAMaterno) :
                new ObjectParameter("nomAMaterno", typeof(string));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrModParameter = usrMod != null ?
                new ObjectParameter("usrMod", usrMod) :
                new ObjectParameter("usrMod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESEdUsuarios", usrAPPParameter, nomNombreParameter, nomAPaternoParameter, nomAMaternoParameter, banActivoParameter, usrModParameter);
        }
    
        public virtual ObjectResult<spRESICnPaginasXUsuario_Result> spRESICnPaginasXUsuario(string usrAPP, Nullable<int> idAplicacion)
        {
            var usrAPPParameter = usrAPP != null ?
                new ObjectParameter("usrAPP", usrAPP) :
                new ObjectParameter("usrAPP", typeof(string));
    
            var idAplicacionParameter = idAplicacion.HasValue ?
                new ObjectParameter("idAplicacion", idAplicacion) :
                new ObjectParameter("idAplicacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRESICnPaginasXUsuario_Result>("spRESICnPaginasXUsuario", usrAPPParameter, idAplicacionParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> spRESICnPermisosPaginaXUsuario(string nomPagina, string usrAPP, Nullable<long> idAplicacion)
        {
            var nomPaginaParameter = nomPagina != null ?
                new ObjectParameter("nomPagina", nomPagina) :
                new ObjectParameter("nomPagina", typeof(string));
    
            var usrAPPParameter = usrAPP != null ?
                new ObjectParameter("usrAPP", usrAPP) :
                new ObjectParameter("usrAPP", typeof(string));
    
            var idAplicacionParameter = idAplicacion.HasValue ?
                new ObjectParameter("idAplicacion", idAplicacion) :
                new ObjectParameter("idAplicacion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("spRESICnPermisosPaginaXUsuario", nomPaginaParameter, usrAPPParameter, idAplicacionParameter);
        }
    
        public virtual int spRESInaAplicacionRol(Nullable<long> idAplicacion, Nullable<long> idRol)
        {
            var idAplicacionParameter = idAplicacion.HasValue ?
                new ObjectParameter("idAplicacion", idAplicacion) :
                new ObjectParameter("idAplicacion", typeof(long));
    
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESInaAplicacionRol", idAplicacionParameter, idRolParameter);
        }
    
        public virtual int spRESInaBackProcess(ObjectParameter idBackProcess, Nullable<long> idAplicacion, string nomProceso, string xmlParamteros, string nomLibreria)
        {
            var idAplicacionParameter = idAplicacion.HasValue ?
                new ObjectParameter("idAplicacion", idAplicacion) :
                new ObjectParameter("idAplicacion", typeof(long));
    
            var nomProcesoParameter = nomProceso != null ?
                new ObjectParameter("nomProceso", nomProceso) :
                new ObjectParameter("nomProceso", typeof(string));
    
            var xmlParamterosParameter = xmlParamteros != null ?
                new ObjectParameter("xmlParamteros", xmlParamteros) :
                new ObjectParameter("xmlParamteros", typeof(string));
    
            var nomLibreriaParameter = nomLibreria != null ?
                new ObjectParameter("nomLibreria", nomLibreria) :
                new ObjectParameter("nomLibreria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESInaBackProcess", idBackProcess, idAplicacionParameter, nomProcesoParameter, xmlParamterosParameter, nomLibreriaParameter);
        }
    
        public virtual int spRESInaBackProcessLog(ObjectParameter idaBackProcessLog, Nullable<int> idBackProcess, string resultado)
        {
            var idBackProcessParameter = idBackProcess.HasValue ?
                new ObjectParameter("idBackProcess", idBackProcess) :
                new ObjectParameter("idBackProcess", typeof(int));
    
            var resultadoParameter = resultado != null ?
                new ObjectParameter("Resultado", resultado) :
                new ObjectParameter("Resultado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESInaBackProcessLog", idaBackProcessLog, idBackProcessParameter, resultadoParameter);
        }
    
        public virtual int spRESInaLogError(ObjectParameter idLogError, Nullable<int> idCapa, Nullable<int> idSeveridad, Nullable<long> idAplicacion, string server, string nomPagina, string metodo, string descripcion, string usrAlta)
        {
            var idCapaParameter = idCapa.HasValue ?
                new ObjectParameter("idCapa", idCapa) :
                new ObjectParameter("idCapa", typeof(int));
    
            var idSeveridadParameter = idSeveridad.HasValue ?
                new ObjectParameter("idSeveridad", idSeveridad) :
                new ObjectParameter("idSeveridad", typeof(int));
    
            var idAplicacionParameter = idAplicacion.HasValue ?
                new ObjectParameter("idAplicacion", idAplicacion) :
                new ObjectParameter("idAplicacion", typeof(long));
    
            var serverParameter = server != null ?
                new ObjectParameter("server", server) :
                new ObjectParameter("server", typeof(string));
    
            var nomPaginaParameter = nomPagina != null ?
                new ObjectParameter("nomPagina", nomPagina) :
                new ObjectParameter("nomPagina", typeof(string));
    
            var metodoParameter = metodo != null ?
                new ObjectParameter("Metodo", metodo) :
                new ObjectParameter("Metodo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var usrAltaParameter = usrAlta != null ?
                new ObjectParameter("usrAlta", usrAlta) :
                new ObjectParameter("usrAlta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESInaLogError", idLogError, idCapaParameter, idSeveridadParameter, idAplicacionParameter, serverParameter, nomPaginaParameter, metodoParameter, descripcionParameter, usrAltaParameter);
        }
    
        public virtual int spRESInaPermisoEspecial(string usrAPP, Nullable<long> idPagina, Nullable<long> idPermiso, Nullable<bool> banActivo, string usrAlta)
        {
            var usrAPPParameter = usrAPP != null ?
                new ObjectParameter("usrAPP", usrAPP) :
                new ObjectParameter("usrAPP", typeof(string));
    
            var idPaginaParameter = idPagina.HasValue ?
                new ObjectParameter("idPagina", idPagina) :
                new ObjectParameter("idPagina", typeof(long));
    
            var idPermisoParameter = idPermiso.HasValue ?
                new ObjectParameter("idPermiso", idPermiso) :
                new ObjectParameter("idPermiso", typeof(long));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrAltaParameter = usrAlta != null ?
                new ObjectParameter("usrAlta", usrAlta) :
                new ObjectParameter("usrAlta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESInaPermisoEspecial", usrAPPParameter, idPaginaParameter, idPermisoParameter, banActivoParameter, usrAltaParameter);
        }
    
        public virtual int spRESInaRolPaginaPermiso(Nullable<long> idRol, Nullable<long> idPagina, Nullable<long> idPermiso, Nullable<bool> banActivo, string usrAlta)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(long));
    
            var idPaginaParameter = idPagina.HasValue ?
                new ObjectParameter("idPagina", idPagina) :
                new ObjectParameter("idPagina", typeof(long));
    
            var idPermisoParameter = idPermiso.HasValue ?
                new ObjectParameter("idPermiso", idPermiso) :
                new ObjectParameter("idPermiso", typeof(long));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrAltaParameter = usrAlta != null ?
                new ObjectParameter("usrAlta", usrAlta) :
                new ObjectParameter("usrAlta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESInaRolPaginaPermiso", idRolParameter, idPaginaParameter, idPermisoParameter, banActivoParameter, usrAltaParameter);
        }
    
        public virtual int spRESInaRolUsuario(Nullable<long> idRol, string usrAPP, Nullable<bool> banActivo, string usrAlta)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(long));
    
            var usrAPPParameter = usrAPP != null ?
                new ObjectParameter("usrAPP", usrAPP) :
                new ObjectParameter("usrAPP", typeof(string));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrAltaParameter = usrAlta != null ?
                new ObjectParameter("usrAlta", usrAlta) :
                new ObjectParameter("usrAlta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESInaRolUsuario", idRolParameter, usrAPPParameter, banActivoParameter, usrAltaParameter);
        }
    
        public virtual int spRESIncAplicacion(ObjectParameter idAplicacion, string nomAplicacion, Nullable<bool> banActivo, string usrAlta)
        {
            var nomAplicacionParameter = nomAplicacion != null ?
                new ObjectParameter("nomAplicacion", nomAplicacion) :
                new ObjectParameter("nomAplicacion", typeof(string));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrAltaParameter = usrAlta != null ?
                new ObjectParameter("usrAlta", usrAlta) :
                new ObjectParameter("usrAlta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESIncAplicacion", idAplicacion, nomAplicacionParameter, banActivoParameter, usrAltaParameter);
        }
    
        public virtual int spRESIncPagina(ObjectParameter idPagina, Nullable<long> idAplicacion, string nomPagina, Nullable<long> idPaginaPadre, string nomMenu, string url, string imgMenu, Nullable<bool> banActivo, string usrAlta)
        {
            var idAplicacionParameter = idAplicacion.HasValue ?
                new ObjectParameter("idAplicacion", idAplicacion) :
                new ObjectParameter("idAplicacion", typeof(long));
    
            var nomPaginaParameter = nomPagina != null ?
                new ObjectParameter("nomPagina", nomPagina) :
                new ObjectParameter("nomPagina", typeof(string));
    
            var idPaginaPadreParameter = idPaginaPadre.HasValue ?
                new ObjectParameter("idPaginaPadre", idPaginaPadre) :
                new ObjectParameter("idPaginaPadre", typeof(long));
    
            var nomMenuParameter = nomMenu != null ?
                new ObjectParameter("nomMenu", nomMenu) :
                new ObjectParameter("nomMenu", typeof(string));
    
            var urlParameter = url != null ?
                new ObjectParameter("url", url) :
                new ObjectParameter("url", typeof(string));
    
            var imgMenuParameter = imgMenu != null ?
                new ObjectParameter("imgMenu", imgMenu) :
                new ObjectParameter("imgMenu", typeof(string));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrAltaParameter = usrAlta != null ?
                new ObjectParameter("usrAlta", usrAlta) :
                new ObjectParameter("usrAlta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESIncPagina", idPagina, idAplicacionParameter, nomPaginaParameter, idPaginaPadreParameter, nomMenuParameter, urlParameter, imgMenuParameter, banActivoParameter, usrAltaParameter);
        }
    
        public virtual int spRESIncPaginaPermiso(Nullable<long> idPagina, Nullable<long> idPermiso, Nullable<bool> banActivo, string usrAlta)
        {
            var idPaginaParameter = idPagina.HasValue ?
                new ObjectParameter("idPagina", idPagina) :
                new ObjectParameter("idPagina", typeof(long));
    
            var idPermisoParameter = idPermiso.HasValue ?
                new ObjectParameter("idPermiso", idPermiso) :
                new ObjectParameter("idPermiso", typeof(long));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrAltaParameter = usrAlta != null ?
                new ObjectParameter("usrAlta", usrAlta) :
                new ObjectParameter("usrAlta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESIncPaginaPermiso", idPaginaParameter, idPermisoParameter, banActivoParameter, usrAltaParameter);
        }
    
        public virtual int spRESIncPermiso(ObjectParameter idPermiso, string nomPermiso, Nullable<bool> banActivo, string usrAlta)
        {
            var nomPermisoParameter = nomPermiso != null ?
                new ObjectParameter("nomPermiso", nomPermiso) :
                new ObjectParameter("nomPermiso", typeof(string));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrAltaParameter = usrAlta != null ?
                new ObjectParameter("usrAlta", usrAlta) :
                new ObjectParameter("usrAlta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESIncPermiso", idPermiso, nomPermisoParameter, banActivoParameter, usrAltaParameter);
        }
    
        public virtual int spRESIncRol(ObjectParameter idRol, string nomRol, Nullable<bool> banActivo, string usrAlta)
        {
            var nomRolParameter = nomRol != null ?
                new ObjectParameter("nomRol", nomRol) :
                new ObjectParameter("nomRol", typeof(string));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrAltaParameter = usrAlta != null ?
                new ObjectParameter("usrAlta", usrAlta) :
                new ObjectParameter("usrAlta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESIncRol", idRol, nomRolParameter, banActivoParameter, usrAltaParameter);
        }
    
        public virtual int spRESInUsuarios(string usrAPP, string nomNombre, string nomAPaterno, string nomAMaterno, string correo, string providerKey, string provider, string id, string usrAlta)
        {
            var usrAPPParameter = usrAPP != null ?
                new ObjectParameter("usrAPP", usrAPP) :
                new ObjectParameter("usrAPP", typeof(string));
    
            var nomNombreParameter = nomNombre != null ?
                new ObjectParameter("nomNombre", nomNombre) :
                new ObjectParameter("nomNombre", typeof(string));
    
            var nomAPaternoParameter = nomAPaterno != null ?
                new ObjectParameter("nomAPaterno", nomAPaterno) :
                new ObjectParameter("nomAPaterno", typeof(string));
    
            var nomAMaternoParameter = nomAMaterno != null ?
                new ObjectParameter("nomAMaterno", nomAMaterno) :
                new ObjectParameter("nomAMaterno", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var providerKeyParameter = providerKey != null ?
                new ObjectParameter("ProviderKey", providerKey) :
                new ObjectParameter("ProviderKey", typeof(string));
    
            var providerParameter = provider != null ?
                new ObjectParameter("Provider", provider) :
                new ObjectParameter("Provider", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var usrAltaParameter = usrAlta != null ?
                new ObjectParameter("usrAlta", usrAlta) :
                new ObjectParameter("usrAlta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRESInUsuarios", usrAPPParameter, nomNombreParameter, nomAPaternoParameter, nomAMaternoParameter, correoParameter, providerKeyParameter, providerParameter, idParameter, usrAltaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spRESLoginMD5(string usrAPP, string correo)
        {
            var usrAPPParameter = usrAPP != null ?
                new ObjectParameter("usrAPP", usrAPP) :
                new ObjectParameter("usrAPP", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spRESLoginMD5", usrAPPParameter, correoParameter);
        }
    
        public virtual ObjectResult<spRolesCn_Result> spRolesCn()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRolesCn_Result>("spRolesCn");
        }
    
        public virtual int spRolesEd(Nullable<long> idRol, string nomRol, string pagInicio, Nullable<bool> banActivo, string usrMod)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(long));
    
            var nomRolParameter = nomRol != null ?
                new ObjectParameter("nomRol", nomRol) :
                new ObjectParameter("nomRol", typeof(string));
    
            var pagInicioParameter = pagInicio != null ?
                new ObjectParameter("pagInicio", pagInicio) :
                new ObjectParameter("pagInicio", typeof(string));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrModParameter = usrMod != null ?
                new ObjectParameter("usrMod", usrMod) :
                new ObjectParameter("usrMod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRolesEd", idRolParameter, nomRolParameter, pagInicioParameter, banActivoParameter, usrModParameter);
        }
    
        public virtual int spRolesEl(Nullable<long> idRol, Nullable<bool> banActivo, string usrMod)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(long));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrModParameter = usrMod != null ?
                new ObjectParameter("usrMod", usrMod) :
                new ObjectParameter("usrMod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRolesEl", idRolParameter, banActivoParameter, usrModParameter);
        }
    
        public virtual int spRolesIn(string nomRol, string pagInicio, Nullable<bool> banActivo, string usrAlta)
        {
            var nomRolParameter = nomRol != null ?
                new ObjectParameter("nomRol", nomRol) :
                new ObjectParameter("nomRol", typeof(string));
    
            var pagInicioParameter = pagInicio != null ?
                new ObjectParameter("pagInicio", pagInicio) :
                new ObjectParameter("pagInicio", typeof(string));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrAltaParameter = usrAlta != null ?
                new ObjectParameter("usrAlta", usrAlta) :
                new ObjectParameter("usrAlta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRolesIn", nomRolParameter, pagInicioParameter, banActivoParameter, usrAltaParameter);
        }
    
        public virtual int spUsuarioAc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUsuarioAc");
        }
    
        public virtual int spUsuarioEd(string usrAPP, Nullable<long> idEmpleadoJefe, string nomNombre, string nomAPaterno, string nomAMaterno, string correo, Nullable<int> idPuesto, Nullable<bool> banActivo, string usrMod)
        {
            var usrAPPParameter = usrAPP != null ?
                new ObjectParameter("usrAPP", usrAPP) :
                new ObjectParameter("usrAPP", typeof(string));
    
            var idEmpleadoJefeParameter = idEmpleadoJefe.HasValue ?
                new ObjectParameter("idEmpleadoJefe", idEmpleadoJefe) :
                new ObjectParameter("idEmpleadoJefe", typeof(long));
    
            var nomNombreParameter = nomNombre != null ?
                new ObjectParameter("nomNombre", nomNombre) :
                new ObjectParameter("nomNombre", typeof(string));
    
            var nomAPaternoParameter = nomAPaterno != null ?
                new ObjectParameter("nomAPaterno", nomAPaterno) :
                new ObjectParameter("nomAPaterno", typeof(string));
    
            var nomAMaternoParameter = nomAMaterno != null ?
                new ObjectParameter("nomAMaterno", nomAMaterno) :
                new ObjectParameter("nomAMaterno", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var idPuestoParameter = idPuesto.HasValue ?
                new ObjectParameter("idPuesto", idPuesto) :
                new ObjectParameter("idPuesto", typeof(int));
    
            var banActivoParameter = banActivo.HasValue ?
                new ObjectParameter("banActivo", banActivo) :
                new ObjectParameter("banActivo", typeof(bool));
    
            var usrModParameter = usrMod != null ?
                new ObjectParameter("usrMod", usrMod) :
                new ObjectParameter("usrMod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUsuarioEd", usrAPPParameter, idEmpleadoJefeParameter, nomNombreParameter, nomAPaternoParameter, nomAMaternoParameter, correoParameter, idPuestoParameter, banActivoParameter, usrModParameter);
        }
    
        public virtual int spUsuarioIn(string usrAPP, Nullable<long> idEmpleadoJefe, string nomNombre, string nomAPaterno, string nomAMaterno, string correo, Nullable<int> idPuesto, string usrAlta)
        {
            var usrAPPParameter = usrAPP != null ?
                new ObjectParameter("usrAPP", usrAPP) :
                new ObjectParameter("usrAPP", typeof(string));
    
            var idEmpleadoJefeParameter = idEmpleadoJefe.HasValue ?
                new ObjectParameter("idEmpleadoJefe", idEmpleadoJefe) :
                new ObjectParameter("idEmpleadoJefe", typeof(long));
    
            var nomNombreParameter = nomNombre != null ?
                new ObjectParameter("nomNombre", nomNombre) :
                new ObjectParameter("nomNombre", typeof(string));
    
            var nomAPaternoParameter = nomAPaterno != null ?
                new ObjectParameter("nomAPaterno", nomAPaterno) :
                new ObjectParameter("nomAPaterno", typeof(string));
    
            var nomAMaternoParameter = nomAMaterno != null ?
                new ObjectParameter("nomAMaterno", nomAMaterno) :
                new ObjectParameter("nomAMaterno", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var idPuestoParameter = idPuesto.HasValue ?
                new ObjectParameter("idPuesto", idPuesto) :
                new ObjectParameter("idPuesto", typeof(int));
    
            var usrAltaParameter = usrAlta != null ?
                new ObjectParameter("usrAlta", usrAlta) :
                new ObjectParameter("usrAlta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUsuarioIn", usrAPPParameter, idEmpleadoJefeParameter, nomNombreParameter, nomAPaternoParameter, nomAMaternoParameter, correoParameter, idPuestoParameter, usrAltaParameter);
        }
    
        public virtual ObjectResult<spUsuariosNombreCn_Result> spUsuariosNombreCn(Nullable<long> idAplicacion, string nombre)
        {
            var idAplicacionParameter = idAplicacion.HasValue ?
                new ObjectParameter("idAplicacion", idAplicacion) :
                new ObjectParameter("idAplicacion", typeof(long));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spUsuariosNombreCn_Result>("spUsuariosNombreCn", idAplicacionParameter, nombreParameter);
        }
    }
}
